jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.0.0', '1.0.1', '1.0.2']

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v3
        with:
          ref: release/${{ matrix.version }}

      - name: Build Docker image
        run: |
          docker build -t api-gateway:${{ matrix.version }} .

      - name: Push to registry
        run: |
          docker push api-gateway:${{ matrix.version }}
