name: Build & Push Versioned Docker Image

on:
  push:
    branches:
      - release/1.0.0
      - release/1.0.1
      - release/1.0.2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.0.0', '1.0.1', '1.0.2']

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v3
        with:
          ref: release/${{ matrix.version }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t api-gateway:${{ matrix.version }} .

      - name: Push to registry
        run: |
          docker push api-gateway:${{ matrix.version }}
